FROM node:18

WORKDIR /app

COPY frontend/package*.json ./frontend/
RUN cd frontend && npm ci  # ou npm install

COPY frontend/ ./frontend/

RUN cd frontend && npm run build

RUN npm install -g serve

EXPOSE 3000
CMD ["serve", "-s", "frontend/dist", "-l", "3000"]
