FROM python:3.12
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000

COPY /app ./app
COPY /api ./api
COPY manage.py manage.py

CMD ["gunicorn", "app.wsgi:application", "--bind", "0.0.0.0:8000"]